### ISSUE TITLE
MeasureSpec.EXACTLY crash

### ISSUE THREAD

**Issue by theblixguy** [HeinrichReimer/material-drawer#32]
I'm using the latest library and getting the following in log cat:

`
java.lang.IllegalArgumentException: DrawerLayout must be measured with MeasureSpec.EXACTLY.
            at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:814)
            at android.view.View.measure(View.java:16628)
            at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:866)
            at android.view.View.measure(View.java:16628)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16628)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16628)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16628)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16628)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16628)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2298)
            at android.view.View.measure(View.java:16628)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1916)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1113)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1295)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5610)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:212)
            at android.app.ActivityThread.main(ActivityThread.java:5137)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:718)
            at dalvik.system.NativeStart.main(Native Method)
`

**Comment by HeinrichReimer** [comment]
When do you get this error?

**Comment by theblixguy** [comment]
@HeinrichReimer I just migrated from an old version of your library to the latest version, I was using DrawerView so I replaced it with DrawerFrameLayout everywhere in my code and since then I am getting this error

**Comment by HeinrichReimer** [comment]
DrawerFrameLayout is not a replacement for DrawerView. It extends DrawerLayout. For usage See the README vor the example code.

**Comment by theblixguy** [comment]
@HeinrichReimer I tried that as well, same error

**Comment by HeinrichReimer** [comment]
Please send some more information how I can reproduce the error. Which Android version or device are you using. Or send me some parts of your code like the layout XML and your Activity.

**Comment by MishUshakov** [comment]
Hi Guys,i use this library in my Project,in the "onCreate" methode application crash...
Tests:
Android 5.0-Crash
KitKat 4.4.2-Ok
Jelly Bean 4.3-Ok
ICS-Crash
Android 4.0-4.3+5.0=Craaash
I have find the error in Code after creating the drawer the app crash out 
Ps. Sorry for my bad english :(

**Comment by HeinrichReimer** [comment]
@theblixguy Any update on your issue?

**Comment by theblixguy** [comment]
Yeah, I still have the same error. I'll try the newest version of your lib and let you know if it still exists

**Comment by HeinrichReimer** [comment]
Does this error occur when you use material-drawer on a real device or only in the layout editor?

**Comment by theblixguy** [comment]
When I run the app on device

**Comment by HeinrichReimer** [comment]
Just to help me reproducing the problem: can you tell me which device you're using and on what Android version?
Do you use any special type of `Activity` or `LayoutInflater`?

**Comment by theblixguy** [comment]
Xperia Z3 w/ Lollipop 5.0.2

Nope, just a normal action bar activity

**Comment by HeinrichReimer** [comment]
To fix this issue:
1. Send me some extracts of your code (e.g. *layout_main.xml* or *MainActivity.java*...)
2. Describe the steps to reproduce the error.
I hope I can reproduce and then fix it soon :smiley:
