### ISSUE TITLE
Turning on MinifyEnabled will crash app

### ISSUE THREAD

**Issue by alvinwoon** [HeinrichReimer/material-drawer#50]
Reproduced on production build.

03-12 14:40:52.251  29987-29987/com.remu.ootdapp E/PropertyValuesHolder﹕ Couldn't find setter/getter for property colorMatrix with value type class android.graphics.ColorMatrix
03-12 14:40:52.252  29987-29987/com.remu.ootdapp E/PropertyValuesHolder﹕ Couldn't find no-arg method for property colorMatrix: java.lang.NoSuchMethodException: getColorMatrix []
03-12 14:40:52.252  29987-29987/com.remu.ootdapp D/AndroidRuntime﹕ Shutting down VM
03-12 14:40:52.253  29987-29987/com.remu.ootdapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.remu.ootdapp, PID: 29987
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
            at com.c.a.aj.a(Unknown Source)
            at com.c.a.t.d(Unknown Source)
            at com.c.a.ao.d(Unknown Source)
            at com.c.a.ao.a(Unknown Source)
            at com.c.a.ao.a(Unknown Source)
            at com.c.a.t.a(Unknown Source)
            at com.c.a.d.a(Unknown Source)
            at com.heinrichreimersoftware.materialdrawer.DrawerView.c(Unknown Source)
            at com.heinrichreimersoftware.materialdrawer.DrawerView.b(Unknown Source)
            at com.heinrichreimersoftware.materialdrawer.b.d.k(Unknown Source)
            at com.heinrichreimersoftware.materialdrawer.b.d.a(Unknown Source)
            at com.puppylab.firstapp.cj.a(Unknown Source)
            at com.d.a.b.c.run(Unknown Source)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by HeinrichReimer** [comment]
This is caused by NineOldAndroid's `ObjectAnimator` that searches for `getColorMatrix()` and doesn't find it because its name was changed by proguard.
You can either fix this by adding this to your `proguard-rules.pro`:

    -keepclassmembers class com.heinrichreimersoftware.materialdrawer.animation.AlphaSatColorMatrixEvaluator { *; }
    -keepclassmembers class com.heinrichreimersoftware.materialdrawer.animation.AnimatableColorMatrixColorFilter { *; }

...or by waiting for the next (soon released) update. I removed the NineOldAndroids dependency because of its deprecation.
